name: loyality_craft
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  auto_route: ^5.0.4
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  fk_user_agent: ^2.1.0
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  webview_flutter: ^4.0.6

dev_dependencies:
  auto_route_generator: ^5.0.3
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3

flutter:
  uses-material-design: true
