name: loyalit
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  auto_route: ^5.0.4
  cloud_firestore: ^4.4.5
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  fk_user_agent: ^2.1.0
  flutter:
    sdk: flutter
  flutter_screenutil: ^5.7.0
  flutter_svg: ^2.0.4
  get_it: ^7.2.0
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  webview_flutter: ^4.0.6

dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/svg/

  fonts:
    - family: MuseoModerno
      fonts:
        - asset: fonts/MuseoModerno/MuseoModerno-Thin.ttf
          weight: 100
        - asset: fonts/MuseoModerno/MuseoModerno-ExtraLight.ttf
          weight: 200
        - asset: fonts/MuseoModerno/MuseoModerno-Light.ttf
          weight: 300
        - asset: fonts/MuseoModerno/MuseoModerno-Regular.ttf
          weight: 400
        - asset: fonts/MuseoModerno/MuseoModerno-Medium.ttf
          weight: 500
        - asset: fonts/MuseoModerno/MuseoModerno-SemiBold.ttf
          weight: 600
        - asset: fonts/MuseoModerno/MuseoModerno-Bold.ttf
          weight: 700
        - asset: fonts/MuseoModerno/MuseoModerno-ExtraBold.ttf
          weight: 800
        - asset: fonts/MuseoModerno/MuseoModerno-Black.ttf
          weight: 900
    - family: Montserrat
      fonts:
        - asset: fonts/Poppins/Poppins-Thin.ttf
          weight: 100
        - asset: fonts/Poppins/Poppins-ExtraLight.ttf
          weight: 200
        - asset: fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: fonts/Poppins/Poppins-Regular.ttf
          weight: 400
        - asset: fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: fonts/Poppins/Poppins-ExtraBold.ttf
          weight: 800
        - asset: fonts/Poppins/Poppins-Black.ttf
          weight: 900
